### PR TITLE
Refresh the distribution(s) and docker galaxy dependency

### PR DESCRIPTION
**Pull request by brainstorm**
Thanks @johanmeiring for this great role, it can potentially save me up quite a bit of trial and error work with the `ecs-agent` for non-RedHat distros (our use case @umccr). I see you have done a great job following the official AWS docs to install ecs-agent on non-RH distros:

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-install.html

I tried to install it directly from Ansible Galaxy but unfortunately the docker_ubuntu dependency doesn't look like it's in shape?:

```
$ ansible-galaxy install johanmeiring.ubuntu-ecs-agent -p .
- downloading role 'ubuntu-ecs-agent', owned by johanmeiring
- downloading role from https://github.com/johanmeiring/ansible-ubuntu-ecs-agent/archive/v1.1.0.tar.gz
- extracting johanmeiring.ubuntu-ecs-agent to /Users/romanvg/dev/umccrise/deploy/roles/johanmeiring.ubuntu-ecs-agent
- johanmeiring.ubuntu-ecs-agent (v1.1.0) was installed successfully
- adding dependency: angstwad.docker_ubuntu
- downloading role 'docker_ubuntu', owned by angstwad
 [WARNING]: - angstwad.docker_ubuntu was NOT installed successfully: Unable to compare role versions (v1.0, v1.1, v1.1.1, v1.1.6, v1.1.7, v1.1.8, v1.1.9, v1.1.10, v2.0, v2.0.1,
v2.0.2, v2.1.0, v2.1.1, v2.1.2, v2.1.3, v2.1.4, v2.2, v2.2.1, v2.2.2, v2.2.3, v2.3.0, v2.4.0, v2.4.1, v2.4.2, v2.5.0, v2.5.1, v2.5.2, v2.5.3, v3.0.0, v3.1.0, v3.2.0, v3.3.0,
v3.3.1, v3.3.2, v3.3.3, v3.3.4, v3.4.0, v3.4.1, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.5.0, 1.1.5, 1.1.4, 1.1.3, 1.1.2) to determine the most recent version due to
incompatible version formats. Please contact the role author to resolve versioning conflicts, or specify an explicit role version to install.

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

So I took the time to replace the docker role for a more popular/supported one (geerlingguy is quite prolific at Ansible Galaxy), hope it works for you.

Also introduced a few version bumps here and there to keep it up to date with newer distros and so on.

/cc @reisingerf

### CODE REVIEW

**Comment by brainstorm** [comment]
Hm, I might have been a bit too optimistic with this PR, apparently `ecs-agent` cannot be run with such new docker clients, bummer:

```
root@ip-172-31-19-176:/home/ubuntu# docker run -it amazon/amazon-ecs-agent /bin/bash
2018-06-21T01:46:48Z [INFO] Loading configuration
2018-06-21T01:46:48Z [INFO] Amazon ECS agent Version: 1.18.0, Commit: c0defea9
2018-06-21T01:46:48Z [INFO] Unable to get Docker client for version 1.17: version detection check: failed to ping with Docker version: 1.17: Get http://unix.sock/v1.17/version: dial unix /var/run/docker.sock: connect: no such file or directory
2018-06-21T01:46:48Z [INFO] Unable to get Docker client for version 1.18: version detection check: failed to ping with Docker version: 1.18: Get http://unix.sock/v1.18/version: dial unix /var/run/docker.sock: connect: no such file or directory
2018-06-21T01:46:48Z [INFO] Unable to get Docker client for version 1.19: version detection check: failed to ping with Docker version: 1.19: Get http://unix.sock/v1.19/version: dial unix /var/run/docker.sock: connect: no such file or directory
2018-06-21T01:46:48Z [INFO] Unable to get Docker client for version 1.20: version detection check: failed to ping with Docker version: 1.20: Get http://unix.sock/v1.20/version: dial unix /var/run/docker.sock: connect: no such file or directory
2018-06-21T01:46:48Z [INFO] Unable to get Docker client for version 1.21: version detection check: failed to ping with Docker version: 1.21: Get http://unix.sock/v1.21/version: dial unix /var/run/docker.sock: connect: no such file or directory
2018-06-21T01:46:48Z [INFO] Unable to get Docker client for version 1.22: version detection check: failed to ping with Docker version: 1.22: Get http://unix.sock/v1.22/version: dial unix /var/run/docker.sock: connect: no such file or directory
2018-06-21T01:46:48Z [INFO] Unable to get Docker client for version 1.23: version detection check: failed to ping with Docker version: 1.23: Get http://unix.sock/v1.23/version: dial unix /var/run/docker.sock: connect: no such file or directory
2018-06-21T01:46:48Z [INFO] Unable to get Docker client for version 1.24: version detection check: failed to ping with Docker version: 1.24: Get http://unix.sock/v1.24/version: dial unix /var/run/docker.sock: connect: no such file or directory
2018-06-21T01:46:48Z [INFO] Unable to get Docker client for version 1.25: version detection check: failed to ping with Docker version: 1.25: Get http://unix.sock/v1.25/version: dial unix /var/run/docker.sock: connect: no such file or directory
2018-06-21T01:46:48Z [INFO] Unable to get Docker client for version 1.26: version detection check: failed to ping with Docker version: 1.26: Get http://unix.sock/v1.26/version: dial unix /var/run/docker.sock: connect: no such file or directory
2018-06-21T01:46:48Z [INFO] Unable to get Docker client for version 1.27: version detection check: failed to ping with Docker version: 1.27: Get http://unix.sock/v1.27/version: dial unix /var/run/docker.sock: connect: no such file or directory
2018-06-21T01:46:48Z [INFO] Unable to get Docker client for version 1.28: version detection check: failed to ping with Docker version: 1.28: Get http://unix.sock/v1.28/version: dial unix /var/run/docker.sock: connect: no such file or directory
2018-06-21T01:46:48Z [INFO] Unable to get Docker client for version 1.29: version detection check: failed to ping with Docker version: 1.29: Get http://unix.sock/v1.29/version: dial unix /var/run/docker.sock: connect: no such file or directory
2018-06-21T01:46:48Z [INFO] Unable to get Docker client for version 1.30: version detection check: failed to ping with Docker version: 1.30: Get http://unix.sock/v1.30/version: dial unix /var/run/docker.sock: connect: no such file or directory
2018-06-21T01:46:48Z [ERROR] DockerGoClient: unable to connect to Docker daemon. Ensure Docker is running: docker client factory: client not found for docker version: 1.17
2018-06-21T01:46:48Z [CRITICAL] Error creating Docker client: docker client factory: client not found for docker version: 1.17
```

**Comment by brainstorm** [comment]
Managed to make it run properly now:

```
# docker logs -f 0a4d4eab1462
2018-06-21T03:56:03Z [INFO] Loading configuration
2018-06-21T03:56:03Z [INFO] Amazon ECS agent Version: 1.18.0, Commit: c0defea9
2018-06-21T03:56:03Z [INFO] Loading state! module="statemanager"
2018-06-21T03:56:03Z [INFO] Event stream ContainerChange start listening...
2018-06-21T03:56:03Z [INFO] Creating root ecs cgroup: /ecs
2018-06-21T03:56:03Z [INFO] Creating cgroup /ecs
2018-06-21T03:56:03Z [INFO] Registering Instance with ECS
2018-06-21T03:56:03Z [INFO] Registered container instance with cluster!
2018-06-21T03:56:03Z [INFO] Registration completed successfully. I am running as 'arn:aws:ecs:ap-southeast-2:SOMEID:container-instance/ANOTHER_HASH' in cluster 'OUR_CLUSTER'
2018-06-21T03:56:03Z [INFO] Saving state! module="statemanager"
2018-06-21T03:56:03Z [INFO] Beginning Polling for updates
2018-06-21T03:56:03Z [INFO] Event stream DeregisterContainerInstance start listening...
2018-06-21T03:56:03Z [INFO] Initializing stats engine
2018-06-21T03:56:03Z [INFO] NO_PROXY set:169.254.169.254,169.254.170.2,/var/run/docker.sock
2018-06-21T03:56:03Z [INFO] Connected to TCS endpoint
2018-06-21T03:56:03Z [INFO] Connected to ACS endpoint
2018-06-21T03:56:13Z [INFO] Saving state! module="statemanager"
```

But with a gotcha:

```
2018-06-21T03:57:25Z [WARN] Disabling TaskCPUMemLimit because agent is unabled to setup '/ecs' cgroup: cgroup create: unable to create controller: mkdir /sys/fs/cgroup/systemd/ecs: read-only file system
```

Unfortunately I have to run the container with `--privileged` to be able to get those Task CPU metrics:

```bash
docker run --name ecs-agent
           --detach=true     
           --restart=on-failure:10     
           --volume=/var/run/docker.sock:/var/run/docker.sock     
           --volume=/var/log/ecs:/log     
           --volume=/var/lib/ecs/data:/data     
           --net=host     
           --env-file=/etc/ecs/ecs.config     
           --env=ECS_LOGFILE=/log/ecs-agent.log     
           --env=ECS_DATADIR=/data/     
           --env=ECS_ENABLE_TASK_IAM_ROLE=true     
           --env=ECS_ENABLE_TASK_IAM_ROLE_NETWORK_HOST=true  
           --privileged
           amazon/amazon-ecs-agent:make
```

I'll put those changes in place next, not too happy about the `--privileged` flag, but the risk profile doesn't seem to be too high (closed down AWS Batch cluster with our own code, etc..).

**Comment by johanmeiring** [comment]
Hi @brainstorm !  Thanks very much for your patience, and thanks as well for the compliments in your initial message 😄  I'm honestly just happy that someone else will be able to use it, seeing as how our company eventually decided not to (hence the lack of maintenance).

Some comments from my side:

Firstly, I did not get the same results when pulling the role, please see output below:

```
$ ansible-galaxy install johanmeiring.ubuntu-ecs-agent -p .
- downloading role 'ubuntu-ecs-agent', owned by johanmeiring
- downloading role from https://github.com/johanmeiring/ansible-ubuntu-ecs-agent/archive/v1.1.0.tar.gz
- extracting johanmeiring.ubuntu-ecs-agent to /Users/johan/Projects/johanmeiring/some-test/johanmeiring.ubuntu-ecs-agent
- johanmeiring.ubuntu-ecs-agent (v1.1.0) was installed successfully
- adding dependency: angstwad.docker_ubuntu
- downloading role 'docker_ubuntu', owned by angstwad
- downloading role from https://github.com/angstwad/docker.ubuntu/archive/v3.5.2.tar.gz
- extracting angstwad.docker_ubuntu to /Users/johan/Projects/johanmeiring/some-test/angstwad.docker_ubuntu
- angstwad.docker_ubuntu (v3.5.2) was installed successfully
```

I'm using Ansible 2.6.0 at the moment, not sure if that's what makes the difference.  I haven't had serious problems with `angstwad.docker_ubuntu` in the past, and its popularity is on par with geerlingguy's (https://galaxy.ansible.com/angstwad/docker_ubuntu vs https://galaxy.ansible.com/geerlingguy/docker).  But, that being said, I am a fan of geerlingguy's work and use plenty of his other roles in other projects, so I will defer to your judgement in this case.

Then, it's unfortunate that the `privileged` flag will need to be set, but I can't currently find a way around that, or why it's even needed.  I don't think it needs to hold this PR back, but a solution will probably need to be found at some point.

Lastly, it looks like the code is not quite completed at this point (commented code, etc).  Would be great if that can be cleaned-up and finalised.  I'm happy to merge it when you're happy that it will work for your use case, and will then probably tag it as version v2.0.0 (but I will likely also do a final code review when you're done).  Just let me know.

And thanks very much for your contribution!

**Comment by brainstorm** [comment]
Thanks for the comprehensive comments, fair points indeed!

Since by default AWS Batch clusters (our usecase) are inside private VPCs without access to outside, we assessed the `privileged` flag to be a minor issue (otherwise some metrics apparently don't get through).

I decided to intentionally leave the commented blocks just in case there's someone out there who wants to follow the AWS reference documentation to the letter (where they use systemd to manage the docker container)... I found that a bit overkill since the `restart` ansible policy for that docker container works well in practice.

My current iteration of this role seems to work fine, thanks a ton for putting it out there in the first place! ;)

**Comment by johanmeiring** [comment]
I'm happy with this and will be merging it now.  Thank you very much for the contribution :-)

**Pull request merged**
